### PR TITLE
deps: add lxml

### PR DESCRIPTION
**Pull request by chenrui333**
👋 looks like animdl is missing lxml dependency as we found it in [this new formula PR](https://github.com/Homebrew/homebrew-core/pull/121614), thus adding it now. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/124044

### CODE REVIEW

**Comment by justfoolingaround** [comment]
Unfortunately, this cannot be merged.

`lxml` on Windows Python version 3.11 and higher versions cannot install properly. This is why there's a internal dependency resolver for it. If it is placed on the `pyproject.toml` side of things, it would be impossible to install the project on devices that meet those criteria.

This, of course, might get animdl rejected from homebrew but this convenient case for Mac users is not justifiable enough to limit animdl below Python version 3.11 and betray an entire user group!

Please look for alternatives to this if Homebrew devs allow this to but this move of animdl was always thought out in advance!

**Comment by chenrui333** [comment]
> lxml on Windows Python version 3.11 and higher versions cannot install properly. 

Is there any issue tracker for that? Also does poetry has conditional dependency semantics like in setup.py?

**Comment by justfoolingaround** [comment]
Here's the issue tracker for [lxml](https://bugs.launchpad.net/lxml/+bug/1969912), note that the official tracker does not have this. 

I do however want to note that poetry does in fact support environment markers in their requirements spec which I did not see in the past (My applogies for that).

If you can, do change your PR to something like

```toml
lxml = { version = "4.9.0", markers = "sys_platform != 'win32'" }
```

Or I'll do so, see if it works as intended and do so when I get the chance.

**Comment by chenrui333** [comment]
> If you can, do change your PR to something like
> 
> ```toml
> lxml = { version = "4.9.0", markers = "sys_platform != 'win32'" }
> ```

yeah, I can update my PR for it.

**Comment by chenrui333** [comment]
@justfoolingaround done with the change

**Comment by chenrui333** [comment]
gentle ping @justfoolingaround

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/125004

**Review by justfoolingaround — APPROVED** [review]

**Comment by chenrui333** [comment]
np, thanks for catching this. 👍

**Pull request merged**
